apiVersion: v1
kind: Service
metadata:
  name: nginx-proxy-service
spec:
  type: LoadBalancer
  selector:
    app: nginx-proxy
  ports:
    - protocol: TCP
      port: 80           # The port the service exposes
      targetPort: 80     # The container port NGINX listens on
      nodePort: 30081    # External port to access from host
